[build]
  command = "npm uninstall sharp && npm install --platform=linux --arch=x64 --verbose sharp && gatsby build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.20.7"  # Use a specific Node version (e.g., 18 or 20)

[functions]
  external_node_modules = ["sharp"]
  included_files = ["node_modules/sharp/**/*", "lib/**/*"]